template: app-manifests
deployments:
  development:
    target: development
    clusters: 1
    values:
      repository: https://github.com/eedorenko/missionedge-appdev-sample-manifests
      branch: dev
      folder: rancher-hello-world
      zarf_image: ghcr.io/eedorenko/missionedge-appdev-sample-src:zarf
  production:
    target: production
    clusters: 1
    values:
      repository: https://github.com/eedorenko/missionedge-appdev-sample-manifests
      branch: prod
      folder: rancher-hello-world
      zarf_image: ghcr.io/eedorenko/missionedge-appdev-sample-src:zarf


