apiVersion: v1
kind: Service
metadata:
  name: {{  .Values.app.name}}-service
  namespace: {{  .Values.app.workspace}}-{{  .Values.app.name}}-{{  .Values.environment}}
spec:
  selector:
    app: {{  .Values.app.name}}
  ports:
    - protocol: TCP
      port: {{  .Values.port}}
      targetPort: {{  .Values.port}}
